//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/GameCore/Inputs/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""12839c27-4ef0-4009-b54b-724c8a23b5d4"",
            ""actions"": [
                {
                    ""name"": ""StartGame"",
                    ""type"": ""Button"",
                    ""id"": ""bb79ab03-a94b-4efc-8f62-c7d6b235f711"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScreenPosition"",
                    ""type"": ""Value"",
                    ""id"": ""2e7c4b91-50d3-46a0-be2e-5b0169d34fd7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""871495a6-98c7-481b-9479-ad96d09a9d45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeSelect"",
                    ""type"": ""Button"",
                    ""id"": ""b5e10c66-08e0-4628-ae96-9b2074f47780"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnItem1"",
                    ""type"": ""Button"",
                    ""id"": ""3bb52bfc-e8b9-4615-823a-b9e5af623cba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnItem2"",
                    ""type"": ""Button"",
                    ""id"": ""4bee0d3e-3bfb-4b90-b706-e651f2dae9bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnItem3"",
                    ""type"": ""Button"",
                    ""id"": ""4778f853-48a4-4fcf-b180-3529bbba291d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnItem4"",
                    ""type"": ""Button"",
                    ""id"": ""d5d63bd5-14a7-4952-a470-369d85f0bb38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnItem5"",
                    ""type"": ""Button"",
                    ""id"": ""d5705f47-48a8-4aff-b1e8-fdab045c1f1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpawnItem6"",
                    ""type"": ""Button"",
                    ""id"": ""be1441fa-d08d-4d2d-a71a-b682e1393676"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""bd404a89-aefa-40ca-bf68-3e34a5bc8d30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""3cd899e0-d0e8-4e56-88b8-b813785379e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Load"",
                    ""type"": ""Button"",
                    ""id"": ""62f961c2-8120-48a9-bad4-452abd531860"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""647c0948-5091-4b21-a560-f0da41cdfbe8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4582622c-edd9-41b1-88aa-7b453848dc65"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b68fced-8531-4f0c-a0eb-fef8b90f638e"",
                    ""path"": ""<Touchscreen>/touch*/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96245db3-0f13-4a10-951a-3141a4a959d7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfc68f59-fdc5-4f0f-8045-8551bf42b1b5"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7c66829-15d0-4d81-9253-b8bc0ff26dba"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eabfdf72-d0f1-485f-b579-31ca11518af5"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9486a201-3431-49d2-aa94-b5b290d2c356"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnItem4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caf652eb-cecd-4592-aca7-68cc3eb17d85"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnItem5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2aa9d2db-e65d-4f3c-a6c4-f1a6558d7817"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9301fe6e-7c62-4153-939b-4f01b2980d89"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""967de55b-bd2e-4e63-8836-e389232aaf05"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caf3ab8e-47bf-4195-8e99-f6f5db4a8567"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8c2b2e4-0ff5-4274-abb7-acc8c2a33805"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e7de209-4fc8-445a-854c-af16c136de25"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b69a854f-f6de-40c5-88c1-064340e8dd91"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpawnItem6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""df575176-eb9e-4cbf-9de0-80b90a6e172f"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_StartGame = m_Player.FindAction("StartGame", throwIfNotFound: true);
        m_Player_ScreenPosition = m_Player.FindAction("ScreenPosition", throwIfNotFound: true);
        m_Player_Select = m_Player.FindAction("Select", throwIfNotFound: true);
        m_Player_DeSelect = m_Player.FindAction("DeSelect", throwIfNotFound: true);
        m_Player_SpawnItem1 = m_Player.FindAction("SpawnItem1", throwIfNotFound: true);
        m_Player_SpawnItem2 = m_Player.FindAction("SpawnItem2", throwIfNotFound: true);
        m_Player_SpawnItem3 = m_Player.FindAction("SpawnItem3", throwIfNotFound: true);
        m_Player_SpawnItem4 = m_Player.FindAction("SpawnItem4", throwIfNotFound: true);
        m_Player_SpawnItem5 = m_Player.FindAction("SpawnItem5", throwIfNotFound: true);
        m_Player_SpawnItem6 = m_Player.FindAction("SpawnItem6", throwIfNotFound: true);
        m_Player_Reset = m_Player.FindAction("Reset", throwIfNotFound: true);
        m_Player_Save = m_Player.FindAction("Save", throwIfNotFound: true);
        m_Player_Load = m_Player.FindAction("Load", throwIfNotFound: true);
        m_Player_Delete = m_Player.FindAction("Delete", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_StartGame;
    private readonly InputAction m_Player_ScreenPosition;
    private readonly InputAction m_Player_Select;
    private readonly InputAction m_Player_DeSelect;
    private readonly InputAction m_Player_SpawnItem1;
    private readonly InputAction m_Player_SpawnItem2;
    private readonly InputAction m_Player_SpawnItem3;
    private readonly InputAction m_Player_SpawnItem4;
    private readonly InputAction m_Player_SpawnItem5;
    private readonly InputAction m_Player_SpawnItem6;
    private readonly InputAction m_Player_Reset;
    private readonly InputAction m_Player_Save;
    private readonly InputAction m_Player_Load;
    private readonly InputAction m_Player_Delete;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartGame => m_Wrapper.m_Player_StartGame;
        public InputAction @ScreenPosition => m_Wrapper.m_Player_ScreenPosition;
        public InputAction @Select => m_Wrapper.m_Player_Select;
        public InputAction @DeSelect => m_Wrapper.m_Player_DeSelect;
        public InputAction @SpawnItem1 => m_Wrapper.m_Player_SpawnItem1;
        public InputAction @SpawnItem2 => m_Wrapper.m_Player_SpawnItem2;
        public InputAction @SpawnItem3 => m_Wrapper.m_Player_SpawnItem3;
        public InputAction @SpawnItem4 => m_Wrapper.m_Player_SpawnItem4;
        public InputAction @SpawnItem5 => m_Wrapper.m_Player_SpawnItem5;
        public InputAction @SpawnItem6 => m_Wrapper.m_Player_SpawnItem6;
        public InputAction @Reset => m_Wrapper.m_Player_Reset;
        public InputAction @Save => m_Wrapper.m_Player_Save;
        public InputAction @Load => m_Wrapper.m_Player_Load;
        public InputAction @Delete => m_Wrapper.m_Player_Delete;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @StartGame.started += instance.OnStartGame;
            @StartGame.performed += instance.OnStartGame;
            @StartGame.canceled += instance.OnStartGame;
            @ScreenPosition.started += instance.OnScreenPosition;
            @ScreenPosition.performed += instance.OnScreenPosition;
            @ScreenPosition.canceled += instance.OnScreenPosition;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @DeSelect.started += instance.OnDeSelect;
            @DeSelect.performed += instance.OnDeSelect;
            @DeSelect.canceled += instance.OnDeSelect;
            @SpawnItem1.started += instance.OnSpawnItem1;
            @SpawnItem1.performed += instance.OnSpawnItem1;
            @SpawnItem1.canceled += instance.OnSpawnItem1;
            @SpawnItem2.started += instance.OnSpawnItem2;
            @SpawnItem2.performed += instance.OnSpawnItem2;
            @SpawnItem2.canceled += instance.OnSpawnItem2;
            @SpawnItem3.started += instance.OnSpawnItem3;
            @SpawnItem3.performed += instance.OnSpawnItem3;
            @SpawnItem3.canceled += instance.OnSpawnItem3;
            @SpawnItem4.started += instance.OnSpawnItem4;
            @SpawnItem4.performed += instance.OnSpawnItem4;
            @SpawnItem4.canceled += instance.OnSpawnItem4;
            @SpawnItem5.started += instance.OnSpawnItem5;
            @SpawnItem5.performed += instance.OnSpawnItem5;
            @SpawnItem5.canceled += instance.OnSpawnItem5;
            @SpawnItem6.started += instance.OnSpawnItem6;
            @SpawnItem6.performed += instance.OnSpawnItem6;
            @SpawnItem6.canceled += instance.OnSpawnItem6;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
            @Save.started += instance.OnSave;
            @Save.performed += instance.OnSave;
            @Save.canceled += instance.OnSave;
            @Load.started += instance.OnLoad;
            @Load.performed += instance.OnLoad;
            @Load.canceled += instance.OnLoad;
            @Delete.started += instance.OnDelete;
            @Delete.performed += instance.OnDelete;
            @Delete.canceled += instance.OnDelete;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @StartGame.started -= instance.OnStartGame;
            @StartGame.performed -= instance.OnStartGame;
            @StartGame.canceled -= instance.OnStartGame;
            @ScreenPosition.started -= instance.OnScreenPosition;
            @ScreenPosition.performed -= instance.OnScreenPosition;
            @ScreenPosition.canceled -= instance.OnScreenPosition;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @DeSelect.started -= instance.OnDeSelect;
            @DeSelect.performed -= instance.OnDeSelect;
            @DeSelect.canceled -= instance.OnDeSelect;
            @SpawnItem1.started -= instance.OnSpawnItem1;
            @SpawnItem1.performed -= instance.OnSpawnItem1;
            @SpawnItem1.canceled -= instance.OnSpawnItem1;
            @SpawnItem2.started -= instance.OnSpawnItem2;
            @SpawnItem2.performed -= instance.OnSpawnItem2;
            @SpawnItem2.canceled -= instance.OnSpawnItem2;
            @SpawnItem3.started -= instance.OnSpawnItem3;
            @SpawnItem3.performed -= instance.OnSpawnItem3;
            @SpawnItem3.canceled -= instance.OnSpawnItem3;
            @SpawnItem4.started -= instance.OnSpawnItem4;
            @SpawnItem4.performed -= instance.OnSpawnItem4;
            @SpawnItem4.canceled -= instance.OnSpawnItem4;
            @SpawnItem5.started -= instance.OnSpawnItem5;
            @SpawnItem5.performed -= instance.OnSpawnItem5;
            @SpawnItem5.canceled -= instance.OnSpawnItem5;
            @SpawnItem6.started -= instance.OnSpawnItem6;
            @SpawnItem6.performed -= instance.OnSpawnItem6;
            @SpawnItem6.canceled -= instance.OnSpawnItem6;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
            @Save.started -= instance.OnSave;
            @Save.performed -= instance.OnSave;
            @Save.canceled -= instance.OnSave;
            @Load.started -= instance.OnLoad;
            @Load.performed -= instance.OnLoad;
            @Load.canceled -= instance.OnLoad;
            @Delete.started -= instance.OnDelete;
            @Delete.performed -= instance.OnDelete;
            @Delete.canceled -= instance.OnDelete;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnStartGame(InputAction.CallbackContext context);
        void OnScreenPosition(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDeSelect(InputAction.CallbackContext context);
        void OnSpawnItem1(InputAction.CallbackContext context);
        void OnSpawnItem2(InputAction.CallbackContext context);
        void OnSpawnItem3(InputAction.CallbackContext context);
        void OnSpawnItem4(InputAction.CallbackContext context);
        void OnSpawnItem5(InputAction.CallbackContext context);
        void OnSpawnItem6(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnSave(InputAction.CallbackContext context);
        void OnLoad(InputAction.CallbackContext context);
        void OnDelete(InputAction.CallbackContext context);
    }
}
